[programs.localnet]
pythaplex = "CBHQsfr9CSKgqbGBXdc6U9JuhmfCDBzagERt3YvgGDD3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/JustaJunk/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
