[programs.localnet]
pythaplex = "AatFTSmVdF4G6zdbqoUVfLJUq72FQSXuNwveSEkRJPQY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/JustaJunk/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
